Database test again
kota1130/task_test pull request #4
Opened 2020-10-12 15:43 UTC by kota1130

再度データベース接続と一覧表示の課題に取り組みました。

2020-10-19 07:32 UTC, YukiNei-Lev requested changes
コメントしましたので確認お願いします。

2020-10-19 07:32 UTC, YukiNei-Lev commented on resources/views/user_list.blade.php
> +    @endforeach
細かいところですが、現場レベルだとインデントをきちんと揃えるなどはソースの可読性の観点から必須のところなので、勉強の段階から意識づけを行っておいた方がいいですね。
```suggestion
@foreach($users as $user)
        
       id: {{$user->id}}<br>
       user_id: {{$user->user_id}}<br>
       password: {{$user->password}}<br>
       =========================<br>
   
        
@endforeach
```

2020-10-19 07:32 UTC, YukiNei-Lev commented on resources/views/user_list.blade.php
> +       =========================<br>
ここはお勉強レベルでもHTMLのTable要素で表形式表示させておきたいですね。

2020-10-19 07:32 UTC, YukiNei-Lev commented on resources/views/user_list.blade.php
> +    @endforeach
bladeはViewの領域で、最終的なHTMLを記載する場所になります。
HTMLにも最低限のお作法があるので、そのお作法の範囲は少なくとも書いた方が良いですね。
（html/head/body要素の構成になるところなど。）

2020-10-19 07:32 UTC, YukiNei-Lev commented on app/Http/Controllers/UsersController.php
> +        $users = \DB::select('select * from users');
この書き方は、SQLを直接PHPソース上に記載してデータを取得するやり方ですが、LaravelのEloquentの機能を理解すると、SQLを書かなくてもデータの取得・作成・更新・削除ができることがわかると思います。
以下のURLを参照して、SQLを書かずにデータを取得する方法を実現してみてください。
https://readouble.com/laravel/6.x/ja/eloquent.html

2020-10-25 16:12 UTC, kota1130 commented on resources/views/user_list.blade.php
> +    @endforeach
ご指摘ありがとうございます。
こちら修正したファイルを再コミットいたしました。

2020-10-25 16:13 UTC, kota1130 commented on resources/views/user_list.blade.php
> +       =========================<br>
ご指摘ありがとうございます。
Table要素にて表記を完了しました。

2020-10-25 16:13 UTC, kota1130 commented on resources/views/user_list.blade.php
> +    @endforeach
ご指摘ありがとうございます。
こちらもいただいたアドバイスをもとに修正いたしました。

2020-10-25 16:14 UTC, kota1130 commented on app/Http/Controllers/UsersController.php
> +        $users = \DB::select('select * from users');
ご指摘ありがとうございます。
こちらも修正完了し、再コミットいたしました。
お忙しいところ、おそれいりますがご確認頂けますと幸いでございます。

2020-11-12 09:36 UTC, YukiNei-Lev requested changes
コメント＆指摘しました。
ご確認お願いします。

2020-11-12 09:36 UTC, YukiNei-Lev commented on Models/User.php
> +    protected $table = 'users';
この定義はModelクラスの命名とテーブルの命名が規則に沿っていない場合に、対応させるために使うものです。
今回は、テーブル名：Userの複数形、Modelクラス：Userの単数形と、Laravelが自動的にModelクラスとDBのテーブルをマッピングしてくれる形で作られているので不要です。

もう少し補足すると、、、
Modelクラスのインスタンスには１行分のデータが格納される。
検索などで複数件取得したデータを扱う時は、このインスタンスを複数格納したコレクションクラスで扱われる
＝Userが複数でUsers
という思想で、Model名は単語の単数形、テーブル名は単語の複数形という感じになってます。

$tableを使うケースとしては、例えば「企業のマスターテーブル」としてテーブル名をMsCompaniesとしたいが、Model名はMsプレフィックスを取り除いたCompanyにしたいような場合、自動的にModelクラスとDBテーブルが紐付けられないのでModelクラス内で対応するテーブル名を定義する使い方をします。

2020-11-12 09:36 UTC, YukiNei-Lev commented on app/Http/Controllers/UsersController.php
> +        return view('user_list',['users' => $users]);
ControllerからViewに変数を引き渡す時、変数名をそのままで行うのであればcompactというヘルパ関数を使うと可読性が上がります。
```suggestion
        return view('user_list', compact('users'));
```

2020-11-12 09:36 UTC, YukiNei-Lev commented on resources/views/user_list.blade.php
> +    @endforeach
いい感じに変更できてますね！

2020-11-12 09:36 UTC, YukiNei-Lev commented on resources/views/user_list.blade.php
> +
細かいですが、不要な改行は無い方がちゃんとしてるなと思われます。

2020-12-11 08:42 UTC, YukiNei-Lev approved these changes
良い感じにできてるのでApproveしますね。

2020-12-13 13:28 UTC, merged