4つの入門課題に取り組みました
kota1130/task_test pull request #5
Opened 2020-12-25 00:19 UTC by kota1130

下記4つの入門課題に取り組みました。
お忙しい中、誠に恐縮ですが、何卒よろしくお願い申し上げます。
■課題1
ユーザーテーブルを以下の構成で再作成しましょう。
このとき、Laravelのマイグレーション機能で作成を行いましょう。
（https://readouble.com/laravel/6.x/ja/migrations.html）
　【ユーザーテーブル（物理名：「Users」）】
　　・「ID」カラム（物理名「id」）：UNSIGNED INT型・主キー・AUTO_INCREMENT
　　・「ログインID」カラム（物理名「login_id」）：varchar型・100文字・NotNull
　　・「パスワード」カラム（物理名「password」）：varchar型・100文字・NotNull
　　・「姓」カラム（物理名「last_name」）：varchar型・100文字・NotNull
　　・「名」カラム（物理名「first_name」）：varchar型・100文字・NotNull
　　・「性別」カラム（物理名「sex」）：UNSIGNED INT型
　　・「メールアドレス」カラム（物理名「mail_address」）：varchar型・100文字・NotNull
　　・「作成日時」カラム（物理名「created_at」）：timestamp型・NotNull
　　・「最終更新日時」カラム（物理名「updated_at」）：timestamp型・NotNull
　　・「削除日時」カラム（物理名「deleted_at」）：timestamp型
■課題2
課題1で作成したテーブルに対応する形で先に作成した一覧画面を修正しましょう。
（※一覧画面はパスワード以外の項目を表示。）
■課題3
http://127.0.0.1:8000/users/create
にアクセスすると、
①UserController.phpが実行される
②UserControllerからuser_create.blade.phpを呼び出し、画面を表示させる
■課題4
user_create.blade.phpの画面に、「ユーザー登録画面」というタイトルと、以下の入力項目を表示する。
　　・「ログインID」項目（name属性名「login_id」）：テキスト形式
　　・「パスワード」項目（name属性名「password」）：パスワード入力用テキスト形式
　　・「姓」項目（name属性名「last_name」）：テキスト形式
　　・「名」項目（name属性名「first_name」）：テキスト形式
　　・「性別」項目（name属性名「sex」）：ラジオボタン形式（1：男、2：女、3：未設定）
　　・「メールアドレス」項目（name属性名「mail_address」）：テキスト形式

2020-12-25 12:35 UTC, YukiNei-Lev requested changes
Gitで管理すべきファイルは設定ファイルやソースファイルになります。
今添付画像のようにこのPRのFilesChangedの数が5000+（つまり5000ファイル以上）変更や追加が発生しているというのは通常ありえないことです。
（こんなに意図的に設定ファイルやソースファイルは自分で作って無いですよね？）
![image](https://user-images.githubusercontent.com/44665501/103134878-a855e500-46f7-11eb-98ca-1b81c43cebfe.png)

ではなぜこのような状態になっているかというと、作成したソースなどを実際に動かせるようにする際、外部から必要なソースコードを設定にしたがって落としてきたり、アプリケーションの動作高速化などの目的で作成されるキャッシュファイルなどが、Gitでの管理対象としてアップされているからになります。
これらのファイルは履歴管理をする必要がない、またはすべきではないファイルなので、gitignoreと言われるファイルでアップする対象から除外してあげる必要があります。

というところまでが前提の情報になるのですが、ここからが指摘です。
このように管理対象として不適切なファイルまで現在アップロードされている状態ですので、このPRの状態から続ける形で、管理対象にすべきではないファイルをGitから削除し、適切なgitignoreファイルをこのPRでアップしてください。

参考情報：
https://www.hypertextcandy.com/explaining-laravel-project-directories-and-files

2020-12-27 08:52 UTC, kota1130 commented
ご指摘頂きましてありがとうございます。
不要なファイルをアップロードしてしまったが故に、非常にレビューしづらくなってしまい申し訳ございませんでした。

ただいま根井さんからご指摘頂いたことをもとに修正後、再度コミットさせて頂きました。
お忙しいところ恐れ入りますが、お手隙の際にご確認頂けますと幸いでございます。

何卒よろしくお願いいたします。

2021-01-12 04:35 UTC, YukiNei-Lev requested changes
以下のファイルはGit管理に含めるべきではないので除外しましょう。
- bootstrap.zip
- database.zip
- public.zip
- tests.zip
- vendor.zip
- storage/framework 配下全て（※Laravel実行時に動的に作成されるファイル。frameworkディレクトリは残す形で。）
- storage/logs 配下全て（※Laravel実行時に動的に作成されるファイル。logsディレクトリは残す形で。）

2021-01-13 15:34 UTC, kota1130 commented
ご指摘頂きましてありがとうございます。
追加で.gitignoreファイルへ記載をし、除外すべきファイルやディレクトリを管理外へ変更いたしました。
日々、業務のお忙しい中で恐れ入りますがご確認いただけますと幸いです。
何卒よろしくお願いいたします。

2021-01-19 00:55 UTC, YukiNei-Lev commented
.gitignoreの方に記載してもらったのは良いのですが、Files Changedの方に管理すべきじゃ無いファイルが管理対象として認識されたままになってるので、そちらも対応お願いします。

2021-01-30 13:27 UTC, closed without merging